### ISSUE TITLE
How to upload file with ninjato?

### ISSUE THREAD

**Issue by z2058550226** [agoda-com/ninjato#15]

**Comment by Unlimity** [comment]
Hi there! You can pass Java's `File` to the request builders `body` property.

**Comment by free5ty1e** [comment]
It'd be awesome to have an example.  I can't seem to find anything on exactly what that might look like.

**Comment by Unlimity** [comment]
@free5ty1e 
```kotlin
post {
    endpointUrl = "postMyFile"
    body = File("/documents/my.pdf")
}
```
