### ISSUE TITLE
Coroutines and cancellation support

### ISSUE THREAD

**Issue by kartykx** [agoda-com/ninjato#19]
# Feature - Coroutines and cancellation.
Currently Ninjato's http api call, is a blocking method, as we have it below.
https://github.com/agoda-com/ninjato/blob/ae5b8017dfefb137ba57a74b56644314ac4f44f3/clients/client-okhttp/src/main/kotlin/com/agoda/ninjato/client/NinjatoOkHttpClient.kt#L26
## Type
Since coroutines and suspend functions are getting more popular and recommended method in handling threads in Android, wrapping the existing Ninjato's method inside a suspend function makes it non-cancellable. When we cancel the job, it should be relayed to the http layer and we need to remove it from client's queue if it's not already taken.
## Proposed Solution 
We need to enqueue the request on the client, and if the outer scope is canceled, we need to remove the call from the queue.
By doing this instead of just ignoring the result, we are completely stopping it from executing, and it results in great performance  improvement when we have to do some polling and or make some repeated http calls.
```
val call = client.newCall(request).also {           
          it.enqueue(callback)       
} 
ctn.invokeOnCancellation {
            call.cancel()       
}
```

We need to support both blocking and non-blocking api function, and let the user choose which one they want to use. So we need to keep the existing classes untouched and do this as an optional feature.

## Things to do
Update Kotlin version - 1.4.21 (at least)
Add coroutines support - 1.4.2 (at least)

## Working solution
I already have a working solution in which we see a lot of performance improvements. If we think we need this feature, I can take this up and create a PR.

**Comment by kartykx** [comment]
I am willing to take this up

**Comment by Unlimity** [comment]
Hi @kartykx! Thanks for your suggestions and hard work. This does sound useful, however I'm not quite fully understand the implications of your proposed changes. Do you propose to change current library's API to use suspending calls only or you are proposing the ability to run ninjato inside of continuation and cancel enqueued call if the call was in coroutine scope that got cancelled?
Anyway, I would be great to see a contribution from you and we can continue discussion once we take a look at the code 👍

**Comment by karthyks** [comment]
Hi @Unlimity! 
My suggestion is to have both suspending calls and normal blocking calls that we have now. Developers who use this library can choose which class to use, and developers who already use the library will not be affected since we are not gonna change anything on the current blocking calls. 

To explain better, I will create a PR and we can discuss on that.

**Comment by karthyks** [comment]
Do we have a slack channel for this repo?

**Comment by kartykx** [comment]
Hi @Unlimity!
My suggestion is to have both suspending calls and normal blocking calls that we have now. Developers who use this library can choose which class to use, and developers who already use the library will not be affected since we are not gonna change anything on the current blocking calls.

To explain better, I will create a PR and we can discuss on that.

**Comment by kartykx** [comment]
Do we have a slack channel for this repo?

**Comment by Unlimity** [comment]
> Do we have a slack channel for this repo?

Unfortunately, no. And there might be troubles publishing the update, but I'll try to solve it.

**Comment by kartykx** [comment]
I just tried building the sample project, and it crashes due to 404 error, but the url is working on Chrome? Is the sample project broken?

P.S. This is without any changes, from `master` branch.

**Comment by kartykx** [comment]
Hi @Unlimity 
I have proposed an alternative solution to this issue, to avoid duplication. Please have a look #21 

This approach avoids duplication, but there are several changes in existing classes, and I have some naming issues, which I explained in the comment section of the PR.

**Comment by Unlimity** [comment]
@kartykx  thanks for your invaluable contribution! Based on what I observed from your PRs I managed to come up with #22 which adds suspended capabilities as new set of APIs on top of current with minimal impact on current library users.
Is this something that can satisfy your needs? WDYT?

**Comment by kartykx** [comment]
LGTM! Thanks for the quick resolution.
